// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PVWApi.Models;

#nullable disable

namespace PVWApi.Migrations.Celebrante
{
    [DbContext(typeof(CelebranteContext))]
    [Migration("20220915150435_Update Celebrante table")]
    partial class UpdateCelebrantetable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PVWApi.Models.Celebrante", b =>
                {
                    b.Property<int>("CelebranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CelebranteId"), 1L, 1);

                    b.Property<TimeSpan>("HorasContratadas")
                        .HasColumnType("time");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CelebranteId");

                    b.ToTable("Celebrante");
                });

            modelBuilder.Entity("PVWApi.Models.Cerimonia", b =>
                {
                    b.Property<int>("CerimoniaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CerimoniaId"), 1L, 1);

                    b.Property<int>("CelebranteId")
                        .HasColumnType("int");

                    b.Property<bool>("Civil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Religiosa")
                        .HasColumnType("bit");

                    b.HasKey("CerimoniaId");

                    b.HasIndex("CelebranteId");

                    b.ToTable("Cerimonia");
                });

            modelBuilder.Entity("PVWApi.Models.Cerimonia", b =>
                {
                    b.HasOne("PVWApi.Models.Celebrante", null)
                        .WithMany("Cerimonia")
                        .HasForeignKey("CelebranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PVWApi.Models.Celebrante", b =>
                {
                    b.Navigation("Cerimonia");
                });
#pragma warning restore 612, 618
        }
    }
}
