// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PVWApi.Models;

#nullable disable

namespace PVWApi.Migrations.Cerimonia
{
    [DbContext(typeof(CerimoniaContext))]
    partial class CerimoniaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PVWApi.Models.Cerimonia", b =>
                {
                    b.Property<int>("CerimoniaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CerimoniaId"), 1L, 1);

                    b.Property<int>("CelebranteId")
                        .HasColumnType("int");

                    b.Property<bool>("Civil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Religiosa")
                        .HasColumnType("bit");

                    b.HasKey("CerimoniaId");

                    b.ToTable("Cerimonia");
                });
#pragma warning restore 612, 618
        }
    }
}
